#
# This file is part of the CEMD distribution
# Copyright (c) 2022-2026 Jérôme Claverie.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import warnings

import MDAnalysis as mda
import numpy as np

from ...._constants import MASSES_DICT
from .base import BaseReader, BaseWriter

warnings.filterwarnings(
    "ignore", category=UserWarning, module="MDAnalysis.coordinates.PDB"
)
warnings.filterwarnings(
    "ignore", category=UserWarning, module="MDAnalysis.topology.PDBParser"
)


class PDBReader(BaseReader):
    """Read PDB files using MDAnalysis."""

    @classmethod
    def read(cls, path: str) -> dict:
        """Read PDB file."""
        from .mda import MDAReader

        universe = mda.Universe(path)
        universe.atoms.types = [name.capitalize() for name in universe.atoms.names]

        masses = [MASSES_DICT.get(t, 1.0) for t in universe.atoms.types]
        universe.atoms.masses = np.array(masses)

        return MDAReader.read(universe)


class PDBWriter(BaseWriter):
    """Write PDB files."""

    @classmethod
    def write(cls, system, path: str) -> None:
        """Write system to PDB file."""
        lines = []
        lines.append("REMARK   GENERATED BY CEMD (AtomicSystem)")

        box = system.box
        lines.append(
            f"CRYST1{box[0]:9.3f}{box[1]:9.3f}{box[2]:9.3f}"
            f"{box[3]:7.2f}{box[4]:7.2f}{box[5]:7.2f} P 1           1"
        )

        for idx, row in system.atoms.iterrows():
            pdb_id = idx % 100000
            atom_name = str(row["type"]).upper()[:4].center(4)
            element = str(row["type"]).upper()[:2]

            lines.append(
                f"ATOM  {pdb_id:>5} {atom_name} MOL  "
                f"{1:>4}    "
                f"{row['x']:8.3f}{row['y']:8.3f}{row['z']:8.3f}"
                f"{1.0:6.2f}{0.0:6.2f}          "
                f"{element:>2}"
            )

        lines.append("END")
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
