# ===============================================================================
# VMD configuration -CEMD
# ===============================================================================
# Copy this file to ~/.config/cemd/vmd_config.toml
# and modify it as needed.

# ===============================================================================
# General settings
# ===============================================================================

resolution = 12
material = "AOEdgy"

[material_options]
options = ["AOEdgy", "AOShiny", "AOChalky"]

[material_settings]
outlinewidth = 0.6
outline = 1.5
shininess = 0.8

# ===============================================================================
# Element colors (hexadecimal format)
# ===============================================================================

[element_colors]
# Non metals
H  = "#FFFFFF"
C  = "#808080"
O  = "#FF0000"
N  = "#304FF0"
S  = "#FFFF00"
P  = "#FF8000"

# Metalloids
Si = "#F5B800"
B  = "#FFB6C1"

# Halogen
Cl = "#00C2FF"

# Alkali metals
Na = "#4500FA"
K  = "#80E666"
Li = "#B22222"
Rb = "#702670"
Cs = "#8B008B"

# Alkaline earth metals
Ca = "#00E580"
Mg = "#8B4513"
Ba = "#00BFFF"
Sr = "#FF6347"

# Transition metals
Fe = "#FF4500"
Al = "#8080FF"
Ti = "#808080"
Mn = "#9B30FF"
Cr = "#00FF7F"
Ni = "#A9A9A9"
Cu = "#FF6347"
Zn = "#7F7FFF"
Zr = "#94E5FF"
V  = "#FF69B4"
Co = "#FF1493"
Mo = "#C0C0C0"
W  = "#B0C4DE"

# Noble metals
Au = "#FFD700"
Ag = "#C0C0C0"
Pt = "#E5E4E2"
Pd = "#D3D3D3"

# Lanthanides
Ce = "#FFFFE0"
Eu = "#FFE4B5"

# Others
Pb = "#C0C0C0"
U  = "#00FF00"
Th = "#00BFFF"

# ===============================================================================
# Radii of atoms (association types → radius)
# ===============================================================================

[element_radii]
"O" = 0.8
"H" = 0.8
"S" = 0.8
"Si" = 0.8
"C" = 0.8
"Al" = 0.8
"Ca" = 1.8
"Cl" = 1.8
"K" = 1.8
"Na" = 1.8

# ===============================================================================
# Thresholds for connections (association types → cutoff)
# ===============================================================================

[bond_cutoffs]
"O-H" = 1.1
"C-H" = 1.2
"N-H" = 1.2
"N-C" = 1.7
"O-C" = 1.6
"O-S" = 1.6
"O-Si" = 1.75
"O-Al" = 1.75

