#
# This file is part of the CEMD distribution
# Copyright (c) 2024-2026 Jérôme Claverie.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import annotations

import os
import re
# import warnings
import tempfile
from typing import Sequence, TYPE_CHECKING

import numpy as np
import pandas as pd
import scipy.constants as cst
from pymatgen.core import Composition
from pymatgen.core.surface import SlabGenerator
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from .. import AtomicSystem
from .._config import STRUCTURES_DIR
from .._constants import MASSES_DICT
from .._utils import (
    lattice2lammps, 
    lattice2vectors, 
    vectors2lattice
)
from ._packmol import (
    _add_packmol_structure, 
    _get_structure_path,
    _run_packmol
)

if TYPE_CHECKING:
    from cemd.core.atomic_system import AtomicSystem

# warnings.filterwarnings("ignore")

def _sanitize_path(full_path: str) -> str:
    """
    Takes a full path, sanitizes ONLY the filename part to be 
    Packmol-safe, and returns the full reconstructed absolute path.
    """
    directory = os.path.dirname(full_path)
    filename = os.path.basename(full_path)
    
    name, ext = os.path.splitext(filename)
    
    name = name.replace(" ", "_")
    name = re.sub(r'[^a-zA-Z0-9_\-]', '', name)
    
    safe_filename = f"{name}{ext}"
    return os.path.abspath(os.path.join(directory, safe_filename))


def make_surface(data: AtomicSystem, 
                 miller_indices: Sequence[int], 
                 min_slab_size: float=25.0, 
                 min_vacuum_size: float=15.0
                 ) -> tuple[list[AtomicSystem],
                            list[float],
                            list[float],
                            int]:

    if hasattr(data, '_pmg_struct'):
        struct = data._pmg_struct
    else:
        struct = data.to_pmg()
        
    struct.add_oxidation_state_by_guess()
    
    slabgen = SlabGenerator(struct, miller_indices, min_slab_size, min_vacuum_size)

    bonds_dic = {
        ('Al4+', 'O2-') : 1.8,
        ('Al', 'O'): 1.8,
        ('Si4+', 'O2-') : 1.8,
        ('Si', 'O') : 1.8,
        ('C4+', 'O2-') : 1.4,
        ('C', 'O') : 1.4, 
        ('H+', 'O2-') : 1.1,
        ('H', 'O') : 1.1
    }

    # Finding the minimum number of broken links
    i = 0
    slabs_list_pmg = []
    while len(slabs_list_pmg) == 0 and i < 20:
        slabs_list_pmg = slabgen.get_slabs(bonds=bonds_dic, 
                                       max_broken_bonds=i)
        if len(slabs_list_pmg) > 0:
            actual_broken = i
            break
        i += 1
    
    dipole_list = []
    shift_list = []
    for slab in slabs_list_pmg:
        dipole_list.append(abs(slab.dipole[2]))
        shift_list.append(slab.shift)

    slabs_list_as = []
    for i, raw_slab in enumerate(slabs_list_pmg):
        analyzer = SpacegroupAnalyzer(raw_slab)
        slab = analyzer.get_refined_structure()
        slabs_list_as.append(AtomicSystem.from_pymatgen(slab))
    
    return slabs_list_as, shift_list, dipole_list, actual_broken

def make_solution(box: Sequence[float] | np.ndarray = [30,30,30], 
                  density: float=1.0, 
                  solutes_dict: dict[str: int]=None,
                  structures_dict: dict[str: AtomicSystem]=None
                  ) -> AtomicSystem:
    """
    Generate an AtomicSystem representing a liquid solution using Packmol.

    This function automatically determines the number of solvent molecules (H2O) required to reach the target density, accounting for the mass of all 
    provided solutes.

    Parameters
    ----------
    box
        Dimensions of the simulation box in Angstroms [a, b, c]. 
        Defaults to [30, 30, 30].
    density
        Target density of the solution in g/cm³. Defaults to 1.0.
    solutes_dict
        Dictionary mapping solute names (keys) to their respective counts (values). 
        Keys must match either known monatomic ions or entries in structures_dict.
    structures_dict
        Dictionary mapping solute names to their corresponding AtomicSystem objects for complex molecules or custom structures.

    Returns
    -------
    AtomicSystem
        The final system geometry generated by Packmol, with configured 
        box parameters and topology.

    Raises
    ------
    ValueError
        If a solute key is neither a known ion nor found in structures_dict, 
        or if the total mass of solutes exceeds the total mass allowed by 
        the target density and box volume.

    Notes
    -----
    The function currently assumes water (H2O) as the default solvent. 
    Packmol constraints are applied using a 5% safety margin on the box dimensions.
    """

    boxa, boxb, boxc = box[:3]
    vol = boxa * boxb * boxc

    mass_solutes_total_uma = 0
    if solutes_dict:
        for key, num in solutes_dict.items():
            if structures_dict and key in structures_dict:
                mass_solutes_total_uma += num * structures_dict[key].total_mass
            elif key in MASSES_DICT:
                mass_solutes_total_uma += num * MASSES_DICT[key]
            else:
                raise ValueError(f"The structure '{key}' is neither a known ion nor an open tab.")
            
    # calculate the target total mass
    mass_total_target_g = density * vol * 1e-24 
    
    # Convert mass of ions to grams
    mass_ions_g = (mass_solutes_total_uma / cst.Avogadro)
    
    # Deduce the remaining mass of water
    mass_water_g = mass_total_target_g - mass_ions_g
    
    if mass_water_g <= 0:
        raise ValueError("The density or volume is too low to hold all these ions!")

    # Number of water molecules
    water_molarmass = 2 * MASSES_DICT['H'] + MASSES_DICT['O']
    num_water = round((mass_water_g * cst.Avogadro) / water_molarmass)

    with tempfile.TemporaryDirectory(dir='.') as tmp:
        # write packmol input
        structures = []

        h2o_path = _get_structure_path('H2O', tmp)
        structures.append(_add_packmol_structure(
            h2o_path, num_water, 
             (f"inside box 0 0 0 {boxa * 0.95:.4f} {boxb * 0.95:.4f} "
            f"{boxc * 0.95:.4f}")))

        if solutes_dict:
            for key, num in solutes_dict.items():
                if structures_dict and key in structures_dict:
                    safe_path = f"custom_{id(structures_dict[key])}.pdb"
                    struct_path = os.path.join(tmp, safe_path)
                    structures_dict[key].write(struct_path)

                else:
                    struct_path = _get_structure_path(key, tmp)

                struct_path = _sanitize_path(struct_path)
                structures.append(_add_packmol_structure(
                    struct_path, num,
                        "center",
                        (f"inside box 0 0 0 {boxa*0.95:.4f} {boxb*0.95:.4f} "
                        f"{boxc*0.95:.4f}")))

        data = _run_packmol(structures)

    # Print box parameters and number of atoms
    print("\nSolution created")
    print(f"Box size: {boxa:.1f} Å x {boxb:.1f} Å x {boxc:.1f} Å")
    print(f"{num_water} water molecules")
    if solutes_dict:
        for key, num in solutes_dict.items():
            print(f"{num} {key}")

    # Set the box parameters
    if not isinstance(box, list):
        box = box.tolist()

    data.set_box(box + [90, 90, 90])

    return data

def make_glass(box: Sequence[float] | np.ndarray, 
               density: float, 
               stoichiometry_dic: dict[str, float]) -> AtomicSystem:
    """
    Creates an atomic system of glass from a composition of oxides, molecules or atoms.
    """
    
    boxa, boxb, boxc = box
    vol = boxa * boxb * boxc

    total_pattern_mass = 0.0
    atomic_composition = {} 

    for formula, coeff in stoichiometry_dic.items():

        pdb_molecule = os.path.join(STRUCTURES_DIR, f"{formula.lower()}.pdb")
        
        if os.path.exists(pdb_molecule):
            # calculate the mass of the molecule via Pymatgen for the density
            comp = Composition(formula)
            m_part = sum(MASSES_DICT.get(el, 0) * amt for el, amt in comp.get_el_amt_dict().items())
            
            atomic_composition[formula] = atomic_composition.get(formula, 0) + coeff
            total_pattern_mass += m_part * coeff
            
        else:
            # No global PDB, we decompose (e.g.: SiO2, Al2O3)
            try:
                breakdown = Composition(formula).as_dict()
                m_part = 0.0
                for element, amount in breakdown.items():
                    if element not in MASSES_DICT:
                       raise ValueError(f"Missing mass for: {element}")
                    
                    m_part += amount * MASSES_DICT[element]
                    # insert each element separately (eg: “If”, “O”)
                    atomic_composition[element] = atomic_composition.get(element, 0) + (amount * coeff)
                
                total_pattern_mass += m_part * coeff
            except Exception:
                raise ValueError(f"Component '{formula}' not found (no PDB or valid formula)")

    # Calculation of the number of units for the target density
    # n = (rho *V *Na) /M
    num_units = int(np.round((density * vol * 1e-24 * cst.Avogadro) / total_pattern_mass))
    if num_units == 0: num_units = 1

    rho_real = (num_units * total_pattern_mass) / (cst.Avogadro * vol * 1e-24)
    err = (rho_real - density) / density

    # Calling Packmol via temporary directory
    with tempfile.TemporaryDirectory(dir='.') as tmp:

        # Packmol config
        structures = []

        for comp, coeff_in_motif in atomic_composition.items():
            count = int(np.round(coeff_in_motif * num_units))
            if count <= 0: continue
            
            print(f" -> {comp:6s}: {count} unités")
            
            path2structure = _get_structure_path(comp, tmp)
            
            structures.append(_add_packmol_structure(
                path2structure, count,
                "center",
                f"inside box 1 1 1 {boxa-1:.4f} {boxb-1:.4f} {boxc-1:.4f}\n"
            ))

        data = _run_packmol(structures)
        
    # Finalization
    data.set_box(box + [90, 90, 90])
    
    print(f"\nGlass structure generated ({density} g/cm3)")
    print(f"Real density: {rho_real:.3f} g/cm3 (Error: {err*100:.1f}%)")
    

    return data

def add_droplet(solid_system: AtomicSystem, 
                radius: float, 
                density: float = 1.0,
                distance: float = 2.0,
                solutes_dict: dict[str, int] = None, 
                structures_dict: dict[str, AtomicSystem] = None,
                vacuum: float = 10.0) -> AtomicSystem:
    """
    Adds a hemispherical droplet of solution onto a solid surface using 
    add_structure for positioning and merging.
    """
    if isinstance(solid_system, str):
        solid_system = AtomicSystem.from_file(solid_system)

    vol = 2 * np.pi * radius**3 / 3

    mass_solutes_total_uma = 0
    if solutes_dict:
        for key, num in solutes_dict.items():
            if structures_dict and key in structures_dict:
                mass_solutes_total_uma += num * structures_dict[key].total_mass
            elif key in MASSES_DICT:
                mass_solutes_total_uma += num * MASSES_DICT[key]
            else:
                raise ValueError(f"Structure '{key}' mass unknown.")

    mass_total_target_g = density * vol * 1e-24 
    mass_solutes_g = (mass_solutes_total_uma / cst.Avogadro)
    mass_water_g = mass_total_target_g - mass_solutes_g
    
    if mass_water_g <= 0:
        raise ValueError("Density or volume too low for these ions/solutes!")

    water_molarmass = 2 * MASSES_DICT['H'] + MASSES_DICT['O']
    num_water = round((mass_water_g * cst.Avogadro) / water_molarmass)

    with tempfile.TemporaryDirectory(dir='.') as tmp:
        structures = []
        h2o_path = _get_structure_path("H2O", tmp)
        
        structures.append(_add_packmol_structure(h2o_path, num_water, 
            f"inside sphere 0. 0. 0. {radius:.4f}",
            "over plane 0. 0. 1. 0."
        ))

        if solutes_dict:
            for key, num in solutes_dict.items():
                if structures_dict and key in structures_dict:
                    struct_path = os.path.join(tmp, f"custom_{id(structures_dict[key])}.pdb")
                    structures_dict[key].write(struct_path)
                else:
                    struct_path = _get_structure_path(key, tmp)

                struct_path = _sanitize_path(struct_path)
                structures.append(_add_packmol_structure(struct_path, num, 
                        f"inside sphere 0. 0. 0. {radius:.4f}",
                        "over plane 0. 0. 1. 0."
                    ))

        liquid_data = _run_packmol(structures)

    data = add_structure(
        solid_system=solid_system, 
        structure_to_add=liquid_data, 
        distance=distance, 
        axis='z', 
        vacuum=vacuum
    )

    print(f"Droplet added: {num_water} H2O, Radius: {radius} A, Density: {density}")
    
    return data

def add_structure(solid_system: AtomicSystem, 
                  structure_to_add: AtomicSystem, 
                  distance: float = 2.0, 
                  axis: str = 'z',
                  vacuum: float = 10.0) -> AtomicSystem:
    """
    Adds a structure to a solid surface at a given distance, 
    aligning their Centers of Mass (COM) on the transverse axes.
    """
    if isinstance(solid_system, str):
        solid_system = AtomicSystem.from_file(solid_system)
    if isinstance(structure_to_add, str):
        structure_to_add = AtomicSystem.from_file(structure_to_add)
    else:
        structure_to_add = structure_to_add.copy()

    axis_map = {'x': 0, 'y': 1, 'z': 2}
    axis_names = ['x', 'y', 'z']
    idx = axis_map[axis.lower()]
    axis_name = axis_names[idx]
    
    trans_indices = [i for i in [0, 1, 2] if i != idx]
    com_solid = solid_system.get_center_of_mass()
    com_struct = structure_to_add.get_center_of_mass()

    for i in trans_indices:
        t_name = axis_names[i]
        shift_trans = com_solid[i] - com_struct[i]
        structure_to_add.atoms[t_name] += shift_trans

    solid_surface = solid_system.atoms[axis_name].max()
    struct_base = structure_to_add.atoms[axis_name].min()
    
    shift_main = (solid_surface - struct_base) + distance
    structure_to_add.atoms[axis_name] += shift_main

    new_box = solid_system.box.copy()
    solid_min = solid_system.atoms[axis_name].min()
    struct_top = structure_to_add.atoms[axis_name].max()
    
    new_box[idx] = (struct_top - solid_min) + vacuum + distance

    data = merge(solid_system, structure_to_add, new_box)
    data.wrap()

    print(f"Structure added on {axis_name}:")
    
    return data

def add_liquid(solid_system: AtomicSystem, 
               thickness: float, 
               density: float = 1.0,
               distance: float = 2.0,
               solutes_dict: dict[str, int] = None,
               structures_dict: dict[str, AtomicSystem] = None,
               vacuum: float = 0.0, 
               axis: str = 'z') -> AtomicSystem:
    """
    Creates a solid/liquid interface by generating a liquid block and 
    positioning it using the add_structure logic.
    """
    if isinstance(solid_system, str):
        solid_system = AtomicSystem.from_file(solid_system)

    axis_map = {'x': 0, 'y': 1, 'z': 2}
    idx = axis_map[axis.lower()]
    transverse_indices = [i for i in [0, 1, 2] if i != idx]

    boxv_solid = lattice2vectors(solid_system.box)
    dim_transverse_1 = boxv_solid[transverse_indices[0]][transverse_indices[0]]
    dim_transverse_2 = boxv_solid[transverse_indices[1]][transverse_indices[1]]

    liquid_dims = [0, 0, 0]
    liquid_dims[transverse_indices[0]] = dim_transverse_1
    liquid_dims[transverse_indices[1]] = dim_transverse_2
    liquid_dims[idx] = thickness
    
    liquid_data = make_solution(
        box=[liquid_dims[0], liquid_dims[1], liquid_dims[2]], 
        density=density, 
        solutes_dict=solutes_dict, 
        structures_dict=structures_dict
    )

    return add_structure(
        solid_system=solid_system, 
        structure_to_add=liquid_data, 
        distance=distance, 
        axis=axis, 
        vacuum=vacuum
    )

def split(solid_system: AtomicSystem, 
          axis=2,
          coordinate: float=None,
          gap_size: float=20.0,
          tolerance: float=2.0,
          add_solution: bool=True, 
          density: float=1.0,
          solutes_dict: dict[str, int]=None,
          structures_dict: dict[str, AtomicSystem]=None) -> AtomicSystem:
    """
    Splits the atomic system along the specified axis at a given coordinate and optionally inserts a liquid solution in the created gap.
    """
    if isinstance(solid_system, str):
        solid_system = AtomicSystem.from_file(solid_system)

    # GEOMETRY PREPARATION
    vec_list = list(lattice2vectors(solid_system.box))
    target_vec = vec_list[axis]
    unit_norm = target_vec / np.linalg.norm(target_vec)
    L_original = np.linalg.norm(target_vec)
    
    if coordinate is None:
        coordinate = L_original / 2.0
    
    # SPLIT SOLID (Using MDAnalysis fragments to keep molecules intact)
    u = solid_system.to_mda()
    shift_vector = unit_norm * gap_size
    
    # Verification: Are there any connections in the system?
    has_bonds = hasattr(u.atoms, 'bonds') and len(u.atoms.bonds) > 0

    if has_bonds:
        # CASE 1: move by fragments (molecules)
        print("Bonds detected: movement by molecular fragments.")
        for frag in u.atoms.fragments:
            if np.dot(frag.centroid(), unit_norm) >= coordinate:
                frag.positions += shift_vector
    else:
        # CASE 2: No bonds -> move the atoms individually
        print("No bonds detected: atom by atom movement.")
        # Selection of atoms whose projected position is beyond the split
        mask = np.dot(u.atoms.positions, unit_norm) >= coordinate
        u.atoms.positions[mask] += shift_vector
            
    # Update box dimensions
    vec_list[axis] = target_vec + shift_vector
    extended_box = vectors2lattice(tuple(vec_list))
    
    # Create the expanded solid system
    final_system = AtomicSystem.from_mda(u)
    final_system.set_box(extended_box)

    # ADD SOLUTION (Only if requested)
    if add_solution:
        dims = [np.linalg.norm(v) for v in vec_list]
        liquid_thickness = gap_size - (2 * tolerance)
        
        if liquid_thickness <= 0:
            raise ValueError(f"Gap size ({gap_size} Å) is too small for the requested tolerance ({tolerance} Å x 2).")
        
        # Determine transverse dimensions for the liquid box
        other_axes = [i for i in range(3) if i != axis]
        liquid_box_dims = [dims[other_axes[0]], dims[other_axes[1]], liquid_thickness]
        
        # Generate the solution (ensure make_solution is imported)
        liquid_data = make_solution(liquid_box_dims, density, solutes_dict, structures_dict)

        # Positioning: Center the liquid in the middle of the new gap
        gap_center = coordinate + (gap_size / 2.0)
        
        # Project liquid positions on the separation axis
        axis_name = ['x', 'y', 'z'][axis]
        liquid_pos = liquid_data.atoms[axis_name].values
        liquid_center = (np.max(liquid_pos) + np.min(liquid_pos)) / 2.0
        
        # Apply shift to center the liquid block
        liquid_data.atoms[axis_name] += (gap_center - liquid_center)

        # Merge solid and liquid (ensure merge is imported)
        final_system = merge(final_system, liquid_data, extended_box)
        
    return final_system

def merge(lmp_data_a: AtomicSystem, 
          lmp_data_b: AtomicSystem, 
          box:np.ndarray | Sequence[float]=None
          ) -> AtomicSystem:
    '''Merge two LAMMPSData objects and deal with topology issues.'''

    output_topology = {}

    # Set box
    if box is None:
        output_topology['lmp_box'] = lmp_data_a._lmp_box
    else:
        output_topology['lmp_box'] = lattice2lammps(box)
    
    # Merge atoms
    indices_a = lmp_data_a.atoms.index.to_numpy()
    indices_b = lmp_data_b.atoms.index.to_numpy() + lmp_data_a.num_atoms
    merged_indices = np.concatenate([indices_a, indices_b])
    merged_atoms_df = pd.concat([lmp_data_a.atoms, lmp_data_b.atoms], ignore_index=True)
    merged_atoms_df.index = merged_indices
    output_topology['atoms'] = merged_atoms_df

    if lmp_data_a.velocities is not None and lmp_data_b.velocities is not None:
        merged_velocities_df = np.concatenate([lmp_data_a.velocities, lmp_data_b.velocities])
        merged_velocities_df.index = merged_indices
    else:
        output_topology['velocities'] = None

    # Merge masses
    masses_dict_a = {}
    masses_dict_b = {}

    for t, m in zip(lmp_data_a.atom_types, lmp_data_a.masses):
        masses_dict_a[t] = m
    for t, m in zip(lmp_data_b.atom_types, lmp_data_b.masses):
        masses_dict_b[t] = m

    masses_dict_a.update(masses_dict_b)
    sorted_masses_dict_a = dict(sorted(masses_dict_a.items()))
    output_topology['masses'] = sorted_masses_dict_a

    # Merge charges
    charges_dict_a = {}
    charges_dict_b = {}

    for t, m in zip(lmp_data_a.atom_types, lmp_data_a.charges):
        charges_dict_a[t] = m
    for t, m in zip(lmp_data_b.atom_types, lmp_data_b.charges):
        charges_dict_b[t] = m

    charges_dict_a.update(masses_dict_b)
    sorted_charges_dict_a = dict(sorted(charges_dict_a.items()))
    output_topology['charges'] = sorted_charges_dict_a

    output_topology['atom_types'] = list(sorted_masses_dict_a.keys())

    # Get topology info
    connectivity_keys = ['bonds', 'angles', 'dihedrals', 'impropers']
    a_connectivity_dic = {
        'bonds': lmp_data_a.bonds,
        'angles': lmp_data_a.angles,
        'dihedrals': lmp_data_a.dihedrals,
        'impropers': lmp_data_a.impropers
    }
    b_connectivity_dic = {
        'bonds': lmp_data_b.bonds,
        'angles': lmp_data_b.angles,
        'dihedrals': lmp_data_b.dihedrals,
        'impropers': lmp_data_b.impropers
    }

    for key in connectivity_keys:
        if b_connectivity_dic[key] is not None:
            b_connectivity_dic[key].iloc[:,1:] = b_connectivity_dic[key].iloc[:,1:].astype(int) + lmp_data_a.num_atoms
        else:
            b_connectivity_dic[key] = pd.DataFrame()

    for key in connectivity_keys:
        if a_connectivity_dic[key] is None:
            a_connectivity_dic[key] = pd.DataFrame()

    # Set new topology
    for key in connectivity_keys:
        df_merged = pd.concat([a_connectivity_dic[key], b_connectivity_dic[key]], ignore_index=True)

        if key == 'bonds':
            if len(df_merged) != 0:
                output_topology['bonds'] = df_merged
                output_topology['bonds'].index = range(1, len(df_merged) + 1)
            else:
                output_topology['bonds'] = None
            
        if key == 'angles':
            if len(df_merged) != 0:
                output_topology['angles'] = df_merged
                output_topology['angles'].index = range(1, len(df_merged) + 1)
            else:
                output_topology['angles'] = None

        if key == 'dihedrals':
            if len(df_merged) != 0:
                output_topology['dihedrals'] = df_merged
                output_topology['dihedrals'].index = range(1, len(df_merged) + 1)
            else:
                output_topology['dihedrals'] = None

        if key == 'impropers':
            if len(df_merged) != 0:
                output_topology['impropers'] = df_merged
                output_topology['impropers'].index = range(1, len(df_merged) + 1)
            else:
                output_topology['impropers'] = None

    return AtomicSystem(output_topology)

def protonate(data: AtomicSystem, 
              atom_index: int, 
              bond_length: float=1.0) -> AtomicSystem:
    """
    Add a proton (hydrogen atom) to a specific atom in the system.

    The position of the new proton is calculated to be opposite to the 
    center of mass of the target atom's current neighbors to respect 
    local geometry (e.g., VSEPR logic).

    Parameters
    ----------
    data : AtomicSystem
        The atomic system object to modify.
    atom_index : int
        The 0-based integer position (iloc) of the target atom in the 
        `data.atoms` DataFrame.
    bond_length : float, default 1.0
        The distance between the target atom and the new proton in Ångströms.
    proton_type : str, default 'H'
        The type label for the newly created atom.

    Returns
    -------
    data : AtomicSystem
        The modified atomic system with the added proton and updated types/masses.

    Notes
    -----
    If the target atom has no neighbors, the proton is placed along the Z-axis.
    The function automatically updates `data.atom_types` and `data.masses` 
    if a new element is introduced.
    """
    # Extract target atom coordinates using iloc
    target_atom = data.atoms.iloc[atom_index]
    pos_target = target_atom[['x', 'y', 'z']].values.astype(float)
    
    # Determine orientation using MDAnalysis
    u = data.to_mda()
    # MDAnalysis uses 1-based indexing for selection strings
    neighbors = u.select_atoms(f"around 2.2 index {atom_index + 1}")
    
    if len(neighbors) > 0:
        # Calculate direction opposite to the neighbors' center of mass
        pos_neighbors = neighbors.center_of_mass()
        direction = pos_target - pos_neighbors
    else:
        # Default direction if the atom is isolated
        direction = np.array([0, 0, 1.0])
    
    # Normalize the direction vector
    norm = np.linalg.norm(direction)
    if norm < 1e-5: 
        direction = np.array([0, 0, 1.0])
    else:
        direction = direction / norm
    
    # Calculate new position
    new_pos = pos_target + (direction * bond_length)
    
    # USE THE NEW add_atom METHOD
    # This replaces all the manual dictionary/concat/mass logic
    p_mass = MASSES_DICT.get('H', 1.008)
    
    new_id = data.add_atom(
        atype='H',
        position= new_pos,
        charge=+1,   # Or any default charge you prefer
        mass=p_mass
    )

    print(f"DEBUG: Proton added with ID {new_id} via add_atom")

    return data
