#
# This file is part of the CEMD distribution
# Copyright (c) 2022-2026 Jérôme Claverie.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import os
import tempfile
import subprocess
import shutil

from .. import AtomicSystem
from .._paths import STRUCTURES_DIR
from .._constants import MASSES_DICT

def _make_packmol_input(input_name, output_file, structures) -> None:
    '''Create an input file for Packmol'''
    output = "tolerance 1.5\n"
    output += f"output {output_file}\n"
    output += "filetype pdb\n\n"

    for i in structures:
        output += i

    with open(input_name, 'w', encoding='utf-8') as f:
        f.write(output)

def get_structure_path(name: str, temp_dir: str) -> str:
    """
    Returns the path to a PDB file for the given species.
    If it's a known single atom and no PDB exists, generates one in temp_dir.
    """
    # Check if a standard PDB exists (H2O, complex molecules)
    standard_path = os.path.join(STRUCTURES_DIR, f"{name.lower()}.pdb")
    if os.path.exists(standard_path):
        return standard_path

    # If it's a single atom (or ion), generate a temp PDB
    # use name.capitalize() to ensure it's a valid element symbol (Na, Cl...)
    symbol = name.capitalize()
    
    # Simple check: if it's in our masses_dic, we can treat it as an atom
    if symbol in MASSES_DICT:
        temp_pdb = os.path.join(temp_dir, f"{name.lower()}.pdb")
        with open(temp_pdb, 'w') as f:
            f.write("HEADER    Monoatomic species generated by CEMD\n")
            # Format PDB: HETATM id name resname res_id x y z
            f.write(f"HETATM    1 {symbol:2s}  {name.upper():3s}    1       0.000   0.000   0.000\n")
            f.write("END\n")
        return temp_pdb

    raise FileNotFoundError(f"Structure for '{name}' not found and cannot be generated.")

def add_packmol_structure(structure: str, 
                          number: int, 
                          *instructions: str) -> str:
    '''Return a 'structure' section for Packmol'''
    output = f"structure {structure}\n"
    output += f" number {number}\n"
    for i in instructions:
        output += f" {i}\n"
    output += "end structure\n\n"

    return output

def run_packmol(structures: list, 
                 output_path: str = None) -> AtomicSystem | str:
    """Helper to run packmol and return a PDB file or an AtomicSystem."""
    with tempfile.TemporaryDirectory(dir='.') as tmp:
        
        pdb_output_file = os.path.join(tmp, 'tmp_out.pdb')
        packmol_input_file = os.path.join(tmp, 'tmp.inp')

        _make_packmol_input(packmol_input_file, pdb_output_file, structures)
        subprocess.run(f"packmol < {packmol_input_file}", 
                       shell=True, 
                       stdout=subprocess.DEVNULL, 
                       stderr=subprocess.DEVNULL)
        # subprocess.run(f"packmol < {packmol_input_file}", shell=True)

        if not os.path.exists(pdb_output_file):
            raise RuntimeError("Packmol failed to generate output.")

        if output_path is not None:
            shutil.copy(pdb_output_file, output_path)
            return output_path
        return AtomicSystem.from_file(pdb_output_file)


